### ISSUE TITLE
Push iteration limit exceeded

### ISSUE THREAD

**Issue by ofuangka** [Sensory/alexa-rpi#3]
After a few days of running Alexa on a Raspberry Pi 2B, I get the following error:

    ERROR: An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Push iteration limit exceeded.
    INFO:SensoryWakeWordEngine: mainLoop thread ended

I submitted the below issue, but I think this has to do with the snsrRun() function and therefore belongs in this repo.

[https://github.com/alexa/alexa-avs-sample-app/issues/435](https://github.com/alexa/alexa-avs-sample-app/issues/435)

**Comment by JHdeVilliers** [comment]
I've pushed updated code to the update-2 branch that should resolve this issue. Please see  [this comment][1] for installation instructions.

[1]: https://github.com/Sensory/alexa-rpi/issues/6#issuecomment-275557686

**Comment by ofuangka** [comment]
Unfortunately I get the following output after following those instructions.  Did I miss something?

INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-avs.2 | model file: ../ext/resources/spot-alexa-rpi.snsr
WARNING:Library expires on: License expires on 28 May 2017 00:00:00 GMT
ERROR:SensoryWakeWordEngine: Initialization error:Could not load and configure Sensory model: snsrLoad(): License key is not valid for this SDK version.
ERROR:WakeWordAgent: exception in constructor: Could not load and configure Sensory model: snsrLoad(): License key is not valid for this SDK version.
ERROR:main: Exception happened: Could not load and configure Sensory model: snsrLoad(): License key is not valid for this SDK version.

**Comment by JHdeVilliers** [comment]
I've updated the instructions to include an additional step that was mistakenly left out.
In the *samples/wakeWordAgent/sensory/alexa-rpi/* directory:

```
cp ./models/spot-alexa-rpi-31000.snsr ../../ext/resources/spot-alexa-rpi.snsr
```

In other words, copy the the updated *spot-alexa-rpi-31000.snsr* over *spot-alexa-rpi.snsr* in the *samples/wakeWordAgent/ext/resources/* directory.

**Comment by ladsjohn** [comment]
Even with the updated instructions to copy spot-alexa-rpi-31000.snsr; I still get the licensing error:

./wakeWordAgent -e sensory
INFO:main: Starting Wake Word Agent
INFO:WakeWordAgent: State set to IDLE(2)
INFO:Initializing Sensory library | library name: TrulyHandsfree | library version: 5.0.0-avs.2 | model file: ../ext/resources/spot-alexa-rpi.snsr
ERROR:SensoryWakeWordEngine: Initialization error:Could not allocation a new Sensory session: snsrNew(): Library is not licensed.
ERROR:WakeWordAgent: exception in constructor: Could not allocation a new Sensory session: snsrNew(): Library is not licensed.
ERROR:main: Exception happened: Could not allocation a new Sensory session: snsrNew(): Library is not licensed.
INFO:Shutting down Wake Word Agent

**Comment by JHdeVilliers** [comment]
Please double-check that you haven't skipped over steps in the [instructions][1]. The error message you're seeing shows that the license keys were not applied to the new library. You need to run the `./bin/license.sh` step *and accept the agreement* to do this.

[1]: https://github.com/Sensory/alexa-rpi/issues/6#issuecomment-275557686

**Comment by ladsjohn** [comment]
Sorry. Yes. I completely missed the licensing script. Everything is running now. Will monitor for the original issue. It usually takes a day or two. Thanks!

**Comment by ladsjohn** [comment]
Contining to have an issue. Here's the latest failure. Let me know what other data/logs you need. Thnks.


INFO: *** THREAD JOINING: Sensory ***
ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task.fex: Operation failed.
INFO:SensoryWakeWordEngine: mainLoop thread ended
INFO:WakeWordAgent: State set to WAKE_WORD_PAUSED(6)
INFO:WakeWordAgent: IPC Command received:4
INFO:WakeWordAgent: State set to WAKE_WORD_RESUME_REQUESTED(7)
INFO:SensoryWakeWordEngine: handling resume
INFOINFO::SensoryWakeWordEngine: mainLoop thread started
WakeWordAgent: State set to IDLE(2)
ERROR:An error happened in the mainLoop of SensoryWakeWord snsrRun(): task: Push iteration limit exceeded.
INFO:SensoryWakeWordEngine: mainLoop thread ended

**Comment by JHdeVilliers** [comment]
Thanks for the report and the log. This has been a challenging problem to recreate.

**Comment by JHdeVilliers** [comment]
I've pushed another update to the development branch. Please follow the [updated instructions][1] to install the changes.

[1]: https://github.com/Sensory/alexa-rpi/issues/6#issuecomment-275557686

**Comment by JHdeVilliers** [comment]
The update-2 branch fixes were merged into master.
